@tool
extends RefCounted

# Generated by packages/pocket-audio-core/scripts/generate-godot-sound-metadata.mjs.
# Keep this file in sync with pocket-audio-core sound registries.

const LOFI_AUDIO_PROFILE_ID := "lofi_chill"
const DEFAULT_LOFI_PRESET_ID := "lofi_study_room"
const LOFI_STYLE_PRESETS := ["lofi_study_room", "lofi_rainy_window", "lofi_moon_garden", "lofi_koi_pond", "lofi_train_window", "lofi_ant_farm_night", "lofi_menu_warmth", "lofi_sleepy_waltz"]
const LOFI_CHORD_INSTRUMENTS := ["dusty_rhodes", "felt_piano", "cassette_keys", "muted_jazz_guitar", "lofi_warm_pad"]
const LOFI_MELODY_INSTRUMENTS := ["mellow_vibes", "soft_pluck", "mellow_sax", "muted_trumpet", "tape_bell"]
const LOFI_DRUM_KITS := ["lofi_dusty", "lofi_brush", "lofi_tape_soft"]
const LOFI_DRUM_GROOVE_PRESETS := ["lofi_backbeat_76", "lofi_lazy_boom_bap", "lofi_half_time_soft", "lofi_brush_shuffle", "lofi_sparse_clicks", "lofi_sleepy_waltz_3_4"]
const LOFI_BASS_TONES := ["warm_sub", "soft_upright", "rounded_triangle_bass"]
const LOFI_STYLE_PRESET_TEXTURES := {"lofi_study_room": {"enabled": true, "vinylCrackle": 0.09, "tapeHiss": 0.04, "wowFlutter": 0.03, "warmth": 0.18, "lowPassAge": 0.24, "bitCrush": 0.01}, "lofi_rainy_window": {"enabled": true, "vinylCrackle": 0.04, "tapeHiss": 0.1, "wowFlutter": 0.025, "warmth": 0.14, "lowPassAge": 0.2, "bitCrush": 0}, "lofi_moon_garden": {"enabled": true, "vinylCrackle": 0.06, "tapeHiss": 0.05, "wowFlutter": 0.045, "warmth": 0.22, "lowPassAge": 0.18, "bitCrush": 0.01}, "lofi_koi_pond": {"enabled": true, "vinylCrackle": 0.035, "tapeHiss": 0.045, "wowFlutter": 0.02, "warmth": 0.18, "lowPassAge": 0.16, "bitCrush": 0}, "lofi_train_window": {"enabled": true, "vinylCrackle": 0.08, "tapeHiss": 0.06, "wowFlutter": 0.055, "warmth": 0.2, "lowPassAge": 0.28, "bitCrush": 0.018}, "lofi_ant_farm_night": {"enabled": true, "vinylCrackle": 0.05, "tapeHiss": 0.07, "wowFlutter": 0.04, "warmth": 0.18, "lowPassAge": 0.22, "bitCrush": 0.012}, "lofi_menu_warmth": {"enabled": true, "vinylCrackle": 0.03, "tapeHiss": 0.04, "wowFlutter": 0.02, "warmth": 0.16, "lowPassAge": 0.18, "bitCrush": 0}, "lofi_sleepy_waltz": {"enabled": true, "vinylCrackle": 0.035, "tapeHiss": 0.035, "wowFlutter": 0.025, "warmth": 0.14, "lowPassAge": 0.2, "bitCrush": 0}}

const POCKET_DRUM_KITS := ["classic", "lofi_dusty", "lofi_brush", "lofi_tape_soft"]
const POCKET_BASS_TONES := ["classic", "warm_sub", "soft_upright", "rounded_triangle_bass"]
const POCKET_CHORD_INSTRUMENTS := ["pocket", "piano", "saloon_piano", "harp", "warm_pad", "glass", "dusty_rhodes", "felt_piano", "cassette_keys", "muted_jazz_guitar", "lofi_warm_pad"]
const POCKET_MELODY_INSTRUMENTS := ["pulse", "soft", "synth", "bell", "lead_guitar", "distorted_lead_guitar", "banjo", "harmonica", "cowboy_whistle", "trumpet", "saxophone", "mellow_vibes", "soft_pluck", "mellow_sax", "muted_trumpet", "tape_bell"]
const DEFAULT_CHORD_INSTRUMENT := "pocket"
const DEFAULT_MELODY_INSTRUMENT := "pulse"
const GODOT_DRUM_SAMPLE_STREAMS := {"kick": "kick", "kick_accent": "kick_accent", "snare": "snare", "snare_accent": "snare_accent", "hat": "hat", "hat_accent": "hat_accent", "open_hat": "open_hat", "lofi_kick": "lofi_kick", "lofi_snare": "lofi_snare", "lofi_hat": "lofi_hat", "lofi_open_hat": "lofi_open_hat", "clap": "clap", "lofi_dusty:kick": "lofi_dusty_kick", "lofi_dusty:snare": "lofi_dusty_snare", "lofi_dusty:hat": "lofi_dusty_hat", "lofi_dusty:open_hat": "lofi_dusty_open_hat", "lofi_brush:kick": "lofi_brush_kick", "lofi_brush:snare": "lofi_brush_snare", "lofi_brush:hat": "lofi_brush_hat", "lofi_brush:open_hat": "lofi_brush_open_hat", "lofi_tape_soft:kick": "lofi_tape_soft_kick", "lofi_tape_soft:snare": "lofi_tape_soft_snare", "lofi_tape_soft:hat": "lofi_tape_soft_hat", "lofi_tape_soft:open_hat": "lofi_tape_soft_open_hat"}
const GODOT_EVENT_SAMPLE_STREAMS := {"bass": "bass_tone", "bass:auto_bass": "bass_tone", "bass:manual_bass": "bass_tone", "chord": "chord_tone", "chord:tone": "chord_tone", "guitar": "guitar_open", "guitar:open": "guitar_open", "guitar:chug": "guitar_chug", "guitar:accent": "guitar_accent", "guitar:scratch": "guitar_scratch", "melody": "melody_pulse", "bass:classic": "bass_tone", "bass:warm_sub": "bass_warm_sub", "bass:soft_upright": "bass_soft_upright", "bass:rounded_triangle_bass": "bass_rounded_triangle_bass", "chord:pocket": "chord_tone", "chord:piano": "chord_tone", "chord:saloon_piano": "chord_tone", "chord:harp": "chord_tone", "chord:warm_pad": "chord_tone", "chord:glass": "chord_tone", "chord:dusty_rhodes": "chord_dusty_rhodes", "chord:felt_piano": "chord_felt_piano", "chord:cassette_keys": "chord_cassette_keys", "chord:muted_jazz_guitar": "chord_muted_jazz_guitar", "chord:lofi_warm_pad": "chord_lofi_warm_pad", "melody:pulse": "melody_pulse", "melody:soft": "melody_soft", "melody:synth": "melody_pulse", "melody:bell": "melody_bell", "melody:lead_guitar": "melody_pulse", "melody:distorted_lead_guitar": "melody_pulse", "melody:banjo": "melody_pulse", "melody:harmonica": "melody_soft", "melody:cowboy_whistle": "melody_soft", "melody:trumpet": "melody_pulse", "melody:saxophone": "melody_soft", "melody:mellow_vibes": "melody_mellow_vibes", "melody:soft_pluck": "melody_soft_pluck", "melody:mellow_sax": "melody_mellow_sax", "melody:muted_trumpet": "melody_muted_trumpet", "melody:tape_bell": "melody_tape_bell"}

const POCKET_GUITAR_ARTICULATIONS := ["off", "open", "chug", "accent", "hold", "scratch"]
const POCKET_GUITAR_TONES := ["clean", "crunch", "high_gain", "metal", "western_twang"]
const DEFAULT_GUITAR_TONE := "high_gain"
const POCKET_GUITAR_REGISTERS := ["low", "mid", "high"]
const DEFAULT_GUITAR_REGISTER := "low"
const POCKET_GUITAR_STRUM_MODES := ["down", "up", "alternate"]
const DEFAULT_GUITAR_STRUM_MODE := "down"
const POCKET_GUITAR_PATTERN_PRESETS := ["rock_eighths", "punk_downstrokes", "metal_chug", "gallop", "doom_slow", "verse_chorus", "boom_chick", "train_chop", "western_waltz"]

const GAME_PACK_FOLDERS := {"full": "audio/full/", "stems": "audio/stems/", "sections": "audio/sections/", "samples": "audio/samples/", "manifests": "manifests/", "source": "source/"}
const GAME_PACK_MANIFEST_FILES := {"godot-adaptive-pack": "godot-adaptive-manifest.json", "web-game-pack": "web-game-manifest.json"}
const GODOT_GAME_PACK_MANIFEST_PATH := "manifests/godot-adaptive-manifest.json"
const WEB_GAME_PACK_MANIFEST_PATH := "manifests/web-game-manifest.json"
