import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import packageJson from "../package.json" with { type: "json" };

describe("release scripts", () => {
  it("keeps native release bundling explicit", () => {
    const script = readFileSync("scripts/verify-release.mjs", "utf8");
    const itchScript = readFileSync("scripts/verify-itch.mjs", "utf8");
    const packageItch = readFileSync("scripts/package-itch.mjs", "utf8");
    const verifyArtifacts = readFileSync("scripts/verify-release-artifacts.mjs", "utf8");
    const guardedPush = readFileSync("scripts/guarded-butler-push.mjs", "utf8");
    const updaterManifest = readFileSync("scripts/make-updater-manifest.mjs", "utf8");
    const bootstrapperManifest = readFileSync("scripts/make-bootstrapper-manifest.mjs", "utf8");
    const packageBootstrapper = readFileSync("scripts/package-itch-bootstrapper.mjs", "utf8");
    const guardedBootstrapperPush = readFileSync("scripts/guarded-butler-push-bootstrapper.mjs", "utf8");
    const releaseUpdaterBuild = readFileSync("scripts/release-updater-build.mjs", "utf8");

    expect(packageJson.scripts["tauri:build"]).toBe("tauri build");
    expect(packageJson.scripts["verify:native-release"]).toContain("--native-release");
    expect(packageJson.scripts["package:itch"]).toBe("node scripts/package-itch.mjs");
    expect(packageJson.scripts["verify:itch"]).toBe("node scripts/verify-itch.mjs");
    expect(packageJson.scripts["package:itch-bootstrapper"]).toBe("node scripts/package-itch-bootstrapper.mjs");
    expect(packageJson.scripts["verify:itch-bootstrapper"]).toBe("node scripts/verify-itch-bootstrapper.mjs");
    expect(packageJson.scripts["release:itch:local"]).toBe("npm run verify:itch");
    expect(packageJson.scripts["release:updater-manifest"]).toBe("node scripts/make-updater-manifest.mjs");
    expect(packageJson.scripts["release:update"]).toBe("node scripts/release-updater-build.mjs");
    expect(packageJson.scripts["release:update:fast"]).toBe("node scripts/release-updater-build.mjs --fast");
    expect(packageJson.scripts["release:update:full"]).toBe("node scripts/release-updater-build.mjs --full");
    expect(packageJson.scripts["release:update:publish"]).toBe("node scripts/release-updater-build.mjs --full --publish");
    expect(packageJson.scripts["itch:push:bootstrapper"]).toBe("node scripts/guarded-butler-push-bootstrapper.mjs");
    expect(packageJson.scripts["mcp:pocket-daw"]).toContain("pocketDawMcpServer.ts");
    expect(script).toContain('process.argv.includes("--native-release")');
    expect(script).toContain("POCKET_DAW_NATIVE_RELEASE");
    expect(script).toContain('"tauri:debug"');
    expect(script).toContain('"tauri:build"');
    expect(itchScript).toContain('"package:itch"');
    expect(itchScript).toContain('"verify:artifacts"');
    expect(packageItch).toContain('ITCH_CHANNEL = "windows-installer"');
    expect(packageItch).toContain("installerOnly: true");
    expect(packageItch).toContain("publicPortableApp: false");
    expect(packageItch).toContain("rmCurrentVersionReleaseFiles");
    expect(packageItch).toContain("pocket-daw-windows-x64-v${VERSION}");
    expect(packageItch).not.toContain("zip.writeZip");
    expect(packageItch).not.toContain("new AdmZip");
    expect(packageItch).toContain("butler push-preview");
    expect(packageItch).toContain("releases/itch/installers");
    expect(packageItch).toContain("appears stale");
    expect(packageItch).toContain("mix-slider values");
    expect(packageItch).toContain("DAW-vs-Chordsmith browser event parity");
    expect(packageItch).toContain("per-drum lane mixer/FX");
    expect(packageItch).toContain("Godot addon accepts the DAW pack");
    expect(packageItch).toContain("Manual Build Native Cache now immediately swaps active native playback");
    expect(packageItch).toContain("low or zero procedural fallback events");
    expect(packageItch).toContain("Native Playback and Native Cache readouts");
    expect(verifyArtifacts).toContain("assertSignatureFreshness");
    expect(verifyArtifacts).toContain("TAURI_SIGNING_PRIVATE_KEY");
    expect(guardedPush).toContain('PUBLISH !== "1"');
    expect(guardedPush).toContain('"releases/itch/installers"');
    expect(updaterManifest).toContain("pocket-daw-latest.json");
    expect(updaterManifest).toContain("SHA256SUMS.txt");
    expect(bootstrapperManifest).toContain("pocket-daw-bootstrapper-latest.json");
    expect(bootstrapperManifest).toContain("sha256");
    expect(packageBootstrapper).toContain("Get-FileHash -Algorithm SHA256");
    expect(packageBootstrapper).toContain("Start-Process -FilePath $installerPath -Wait");
    expect(guardedBootstrapperPush).toContain('PUBLISH !== "1"');
    expect(guardedBootstrapperPush).toContain('"releases/itch-bootstrapper/upload"');
    expect(releaseUpdaterBuild).toContain("packageItchRelease");
    expect(releaseUpdaterBuild).toContain('process.env.PUBLISH !== "1"');
    expect(releaseUpdaterBuild).toContain("--fast --publish is blocked");
    expect(releaseUpdaterBuild).toContain("makeUpdaterManifest");
    expect(releaseUpdaterBuild).toContain("makeBootstrapperManifest");
    expect(releaseUpdaterBuild).toContain("assertGithubReleaseMissing");
    expect(releaseUpdaterBuild).toContain("Remote setup SHA-256 verified");
    expect(releaseUpdaterBuild).not.toContain('run("butler"');
  });
});
