// Generated by apps/pocket-daw/scripts/generate-native-sound-recipes.mjs.
// Source of truth: packages/pocket-audio-core/src/sounds/* and src/fx/pro-eq.js.
// Do not edit by hand.


fn parametric_eq_filters(params: &std::collections::HashMap<String, serde_json::Value>, sample_rate: f32) -> Vec<BiquadFilter> {
    let mut filters = Vec::new();
    if bool_param(params, "hpEnabled", false) {
        filters.push(BiquadFilter::highpass(
            sample_rate,
            param(params, "hpFrequency", 35.0).clamp(20.0, 1000.0),
            param(params, "hpQ", 0.7).clamp(0.1, 4.0),
        ));
    }
    if bool_param(params, "lowShelfEnabled", true) {
        filters.push(BiquadFilter::shelf(
            sample_rate,
            "lowshelf",
            param(params, "lowShelfFrequency", 120.0).clamp(40.0, 500.0),
            param(params, "lowShelfGain", 0.0).clamp(-12.0, 12.0),
        ));
    }
    if bool_param(params, "lowMidEnabled", true) {
        filters.push(BiquadFilter::peaking(
            sample_rate,
            param(params, "lowMidFrequency", 420.0).clamp(120.0, 2200.0),
            param(params, "lowMidQ", 1.0).clamp(0.2, 8.0),
            param(params, "lowMidGain", 0.0).clamp(-12.0, 12.0),
        ));
    }
    if bool_param(params, "highMidEnabled", true) {
        filters.push(BiquadFilter::peaking(
            sample_rate,
            param(params, "highMidFrequency", 2400.0).clamp(700.0, 8000.0),
            param(params, "highMidQ", 1.0).clamp(0.2, 8.0),
            param(params, "highMidGain", 0.0).clamp(-12.0, 12.0),
        ));
    }
    if bool_param(params, "highShelfEnabled", true) {
        filters.push(BiquadFilter::shelf(
            sample_rate,
            "highshelf",
            param(params, "highShelfFrequency", 8200.0).clamp(2200.0, 18000.0),
            param(params, "highShelfGain", 0.0).clamp(-12.0, 12.0),
        ));
    }
    if bool_param(params, "lpEnabled", false) {
        filters.push(BiquadFilter::lowpass(
            sample_rate,
            param(params, "lpFrequency", 16000.0).clamp(1200.0, 20000.0),
            param(params, "lpQ", 0.7).clamp(0.1, 4.0),
        ));
    }
    filters
}

fn native_drum_kit_config(kit: &str) -> NativeDrumKitConfig {
    match kit {
        "lofi_dusty" => native_drum_kit_lofi_dusty(),
        "lofi_brush" => native_drum_kit_lofi_brush(),
        "lofi_tape_soft" => native_drum_kit_lofi_tape_soft(),
        _ => native_drum_kit_classic(),
    }
}

fn generated_native_resolve_drum_kit(kit: Option<&str>, audio_profile: Option<&str>, lofi_preset: Option<&str>) -> &'static str {
    match kit.unwrap_or("") {
        "classic" => "classic",
        "lofi_dusty" => "lofi_dusty",
        "lofi_brush" => "lofi_brush",
        "lofi_tape_soft" => "lofi_tape_soft",
        _ if generated_native_lofi_active(audio_profile, lofi_preset) => "lofi_dusty",
        _ => "classic",
    }
}

fn generated_native_lofi_active(audio_profile: Option<&str>, lofi_preset: Option<&str>) -> bool {
    audio_profile == Some("lofi_chill") || lofi_preset.unwrap_or("").starts_with("lofi_")
}

fn native_drum_kit_classic() -> NativeDrumKitConfig {
    NativeDrumKitConfig {
        kick: NativeKickConfig {
            start_freq: 155.0,
            end_freq: 45.0,
            sweep_seconds: 0.14,
            filter_freq: None,
            gain_floor: 0.08,
            gain_scale: 1.0,
            length: 0.17,
            ramp_seconds: 0.16,
        },
        snare: NativeSnareConfig {
            noise_seconds: 0.12,
            highpass: 1700.0,
            lowpass: None,
            gain_floor: 0.05,
            gain_scale: 1.0,
            length: 0.13,
            ramp_seconds: 0.12,
            body_freq: None,
            body_gain: 0.0,
            body_length: 0.0,
            body_ramp_seconds: 0.0,
        },
        hat: NativeHatConfig {
            closed_length: 0.05,
            open_length: 0.16,
            highpass_closed: 5600.0,
            highpass_open: 3800.0,
            lowpass: None,
            gain_floor_closed: 0.03,
            gain_floor_open: 0.05,
            gain_scale_closed: 1.0,
            gain_scale_open: 1.0,
            ramp_seconds_closed: 0.05,
            ramp_seconds_open: 0.14,
        },
    }
}

fn native_drum_kit_lofi_dusty() -> NativeDrumKitConfig {
    NativeDrumKitConfig {
        kick: NativeKickConfig {
            start_freq: 132.0,
            end_freq: 42.0,
            sweep_seconds: 0.18,
            filter_freq: Some(170.0),
            gain_floor: 0.04,
            gain_scale: 0.58,
            length: 0.23,
            ramp_seconds: 0.21,
        },
        snare: NativeSnareConfig {
            noise_seconds: 0.13,
            highpass: 980.0,
            lowpass: Some(2800.0),
            gain_floor: 0.035,
            gain_scale: 0.52,
            length: 0.14,
            ramp_seconds: 0.12,
            body_freq: Some(185.0),
            body_gain: 0.035,
            body_length: 0.11,
            body_ramp_seconds: 0.09,
        },
        hat: NativeHatConfig {
            closed_length: 0.065,
            open_length: 0.2,
            highpass_closed: 3400.0,
            highpass_open: 2600.0,
            lowpass: Some(6200.0),
            gain_floor_closed: 0.02,
            gain_floor_open: 0.035,
            gain_scale_closed: 0.55,
            gain_scale_open: 0.62,
            ramp_seconds_closed: 0.055,
            ramp_seconds_open: 0.18,
        },
    }
}

fn native_drum_kit_lofi_brush() -> NativeDrumKitConfig {
    NativeDrumKitConfig {
        kick: NativeKickConfig {
            start_freq: 132.0,
            end_freq: 42.0,
            sweep_seconds: 0.18,
            filter_freq: Some(135.0),
            gain_floor: 0.04,
            gain_scale: 0.48,
            length: 0.23,
            ramp_seconds: 0.21,
        },
        snare: NativeSnareConfig {
            noise_seconds: 0.18,
            highpass: 720.0,
            lowpass: Some(2800.0),
            gain_floor: 0.035,
            gain_scale: 0.46,
            length: 0.2,
            ramp_seconds: 0.18,
            body_freq: Some(150.0),
            body_gain: 0.035,
            body_length: 0.11,
            body_ramp_seconds: 0.09,
        },
        hat: NativeHatConfig {
            closed_length: 0.065,
            open_length: 0.2,
            highpass_closed: 3400.0,
            highpass_open: 2600.0,
            lowpass: Some(6200.0),
            gain_floor_closed: 0.02,
            gain_floor_open: 0.035,
            gain_scale_closed: 0.55,
            gain_scale_open: 0.62,
            ramp_seconds_closed: 0.055,
            ramp_seconds_open: 0.18,
        },
    }
}

fn native_drum_kit_lofi_tape_soft() -> NativeDrumKitConfig {
    NativeDrumKitConfig {
        kick: NativeKickConfig {
            start_freq: 118.0,
            end_freq: 42.0,
            sweep_seconds: 0.18,
            filter_freq: Some(170.0),
            gain_floor: 0.04,
            gain_scale: 0.58,
            length: 0.23,
            ramp_seconds: 0.21,
        },
        snare: NativeSnareConfig {
            noise_seconds: 0.13,
            highpass: 980.0,
            lowpass: Some(2200.0),
            gain_floor: 0.035,
            gain_scale: 0.52,
            length: 0.14,
            ramp_seconds: 0.12,
            body_freq: Some(185.0),
            body_gain: 0.035,
            body_length: 0.11,
            body_ramp_seconds: 0.09,
        },
        hat: NativeHatConfig {
            closed_length: 0.065,
            open_length: 0.2,
            highpass_closed: 3400.0,
            highpass_open: 2600.0,
            lowpass: Some(5200.0),
            gain_floor_closed: 0.02,
            gain_floor_open: 0.035,
            gain_scale_closed: 0.55,
            gain_scale_open: 0.62,
            ramp_seconds_closed: 0.055,
            ramp_seconds_open: 0.18,
        },
    }
}

fn native_bass_tone_config(tone: Option<&str>) -> NativeBassToneConfig {
    match tone.unwrap_or("classic") {
        "warm_sub" => native_bass_tone_warm_sub(),
        "soft_upright" => native_bass_tone_soft_upright(),
        "rounded_triangle_bass" => native_bass_tone_rounded_triangle_bass(),
        _ => native_bass_tone_classic(),
    }
}

fn native_bass_tone_classic() -> NativeBassToneConfig {
    NativeBassToneConfig {
        main_wave: "sawtooth",
        sub_wave: "sine",
        main_peak: 1.0,
        sub_peak: 0.42,
        cutoff: 420.0,
        sub_cutoff: 220.0,
        attack: 0.01,
    }
}

fn native_bass_tone_warm_sub() -> NativeBassToneConfig {
    NativeBassToneConfig {
        main_wave: "sine",
        sub_wave: "sine",
        main_peak: 0.82,
        sub_peak: 0.55,
        cutoff: 210.0,
        sub_cutoff: 120.0,
        attack: 0.018,
    }
}

fn native_bass_tone_soft_upright() -> NativeBassToneConfig {
    NativeBassToneConfig {
        main_wave: "triangle",
        sub_wave: "sine",
        main_peak: 0.72,
        sub_peak: 0.28,
        cutoff: 360.0,
        sub_cutoff: 140.0,
        attack: 0.008,
    }
}

fn native_bass_tone_rounded_triangle_bass() -> NativeBassToneConfig {
    NativeBassToneConfig {
        main_wave: "triangle",
        sub_wave: "sine",
        main_peak: 0.84,
        sub_peak: 0.34,
        cutoff: 300.0,
        sub_cutoff: 130.0,
        attack: 0.012,
    }
}

fn generated_native_chord_config(instrument: Option<&str>) -> NativeChordConfig {
    match instrument.unwrap_or("pocket") {
        "piano" => generated_native_chord_piano(),
        "saloon_piano" => generated_native_chord_saloon_piano(),
        "harp" => generated_native_chord_harp(),
        "warm_pad" => generated_native_chord_warm_pad(),
        "glass" => generated_native_chord_glass(),
        "dusty_rhodes" => generated_native_chord_dusty_rhodes(),
        "felt_piano" => generated_native_chord_felt_piano(),
        "cassette_keys" => generated_native_chord_cassette_keys(),
        "muted_jazz_guitar" => generated_native_chord_muted_jazz_guitar(),
        "lofi_warm_pad" => generated_native_chord_lofi_warm_pad(),
        _ => generated_native_chord_pocket(),
    }
}

const GENERATED_CHORD_POCKET_LAYERS: [NativeChordLayerConfig; 2] = [
    NativeChordLayerConfig {
        wave: "triangle",
        freq_mul: 1.0,
        detune: 0.0,
        level: 0.82,
    },
    NativeChordLayerConfig {
        wave: "sine",
        freq_mul: 1.0,
        detune: 0.0,
        level: 0.35,
    }
];

const GENERATED_CHORD_PIANO_LAYERS: [NativeChordLayerConfig; 2] = [
    NativeChordLayerConfig {
        wave: "triangle",
        freq_mul: 1.0,
        detune: 0.0,
        level: 1.0,
    },
    NativeChordLayerConfig {
        wave: "sine",
        freq_mul: 2.0,
        detune: 3.0,
        level: 0.18,
    }
];

const GENERATED_CHORD_SALOON_PIANO_LAYERS: [NativeChordLayerConfig; 3] = [
    NativeChordLayerConfig {
        wave: "triangle",
        freq_mul: 1.0,
        detune: -8.0,
        level: 0.88,
    },
    NativeChordLayerConfig {
        wave: "triangle",
        freq_mul: 1.0,
        detune: 9.0,
        level: 0.62,
    },
    NativeChordLayerConfig {
        wave: "sine",
        freq_mul: 2.0,
        detune: 5.0,
        level: 0.16,
    }
];

const GENERATED_CHORD_HARP_LAYERS: [NativeChordLayerConfig; 2] = [
    NativeChordLayerConfig {
        wave: "triangle",
        freq_mul: 1.0,
        detune: 0.0,
        level: 0.9,
    },
    NativeChordLayerConfig {
        wave: "sine",
        freq_mul: 2.0,
        detune: 7.0,
        level: 0.26,
    }
];

const GENERATED_CHORD_WARM_PAD_LAYERS: [NativeChordLayerConfig; 2] = [
    NativeChordLayerConfig {
        wave: "sine",
        freq_mul: 1.0,
        detune: -5.0,
        level: 0.95,
    },
    NativeChordLayerConfig {
        wave: "triangle",
        freq_mul: 1.0,
        detune: 6.0,
        level: 0.48,
    }
];

const GENERATED_CHORD_GLASS_LAYERS: [NativeChordLayerConfig; 4] = [
    NativeChordLayerConfig {
        wave: "sine",
        freq_mul: 1.0,
        detune: 0.0,
        level: 0.36,
    },
    NativeChordLayerConfig {
        wave: "sine",
        freq_mul: 2.01,
        detune: 0.0,
        level: 0.64,
    },
    NativeChordLayerConfig {
        wave: "sine",
        freq_mul: 4.02,
        detune: 0.0,
        level: 0.34,
    },
    NativeChordLayerConfig {
        wave: "triangle",
        freq_mul: 6.01,
        detune: 0.0,
        level: 0.12,
    }
];

const GENERATED_CHORD_DUSTY_RHODES_LAYERS: [NativeChordLayerConfig; 3] = [
    NativeChordLayerConfig {
        wave: "triangle",
        freq_mul: 1.0,
        detune: -4.0,
        level: 0.82,
    },
    NativeChordLayerConfig {
        wave: "sine",
        freq_mul: 2.01,
        detune: 5.0,
        level: 0.21,
    },
    NativeChordLayerConfig {
        wave: "sine",
        freq_mul: 3.01,
        detune: -8.0,
        level: 0.045,
    }
];

const GENERATED_CHORD_FELT_PIANO_LAYERS: [NativeChordLayerConfig; 2] = [
    NativeChordLayerConfig {
        wave: "triangle",
        freq_mul: 1.0,
        detune: 0.0,
        level: 0.78,
    },
    NativeChordLayerConfig {
        wave: "sine",
        freq_mul: 2.0,
        detune: -3.0,
        level: 0.16,
    }
];

const GENERATED_CHORD_CASSETTE_KEYS_LAYERS: [NativeChordLayerConfig; 3] = [
    NativeChordLayerConfig {
        wave: "triangle",
        freq_mul: 1.0,
        detune: -9.0,
        level: 0.72,
    },
    NativeChordLayerConfig {
        wave: "triangle",
        freq_mul: 1.0,
        detune: 10.0,
        level: 0.5,
    },
    NativeChordLayerConfig {
        wave: "sine",
        freq_mul: 2.0,
        detune: 3.0,
        level: 0.12,
    }
];

const GENERATED_CHORD_MUTED_JAZZ_GUITAR_LAYERS: [NativeChordLayerConfig; 2] = [
    NativeChordLayerConfig {
        wave: "triangle",
        freq_mul: 1.0,
        detune: 0.0,
        level: 0.8,
    },
    NativeChordLayerConfig {
        wave: "square",
        freq_mul: 1.0,
        detune: -5.0,
        level: 0.11,
    }
];

const GENERATED_CHORD_LOFI_WARM_PAD_LAYERS: [NativeChordLayerConfig; 2] = [
    NativeChordLayerConfig {
        wave: "sine",
        freq_mul: 1.0,
        detune: -7.0,
        level: 0.92,
    },
    NativeChordLayerConfig {
        wave: "triangle",
        freq_mul: 1.0,
        detune: 7.0,
        level: 0.42,
    }
];

fn generated_native_chord_pocket() -> NativeChordConfig {
    NativeChordConfig {
        root_wave: "triangle",
        wave: "sine",
        peak: 0.24,
        filter: "lowpass",
        freq: 1800.0,
        filter_q: 0.8,
        filter_sweep: None,
        attack: 0.01,
        decay: 0.06,
        sustain: 0.7,
        release: 0.2,
        dur_mul: 1.0,
        spread_mul: 1.0,
        shimmer: false,
        max_live_dur: 1.15,
        layers: &GENERATED_CHORD_POCKET_LAYERS,
    }
}

fn generated_native_chord_piano() -> NativeChordConfig {
    NativeChordConfig {
        root_wave: "triangle",
        wave: "triangle",
        peak: 0.23,
        filter: "lowpass",
        freq: 3100.0,
        filter_q: 0.9,
        filter_sweep: None,
        attack: 0.003,
        decay: 0.18,
        sustain: 0.18,
        release: 0.16,
        dur_mul: 0.72,
        spread_mul: 0.45,
        shimmer: false,
        max_live_dur: 0.82,
        layers: &GENERATED_CHORD_PIANO_LAYERS,
    }
}

fn generated_native_chord_saloon_piano() -> NativeChordConfig {
    NativeChordConfig {
        root_wave: "triangle",
        wave: "triangle",
        peak: 0.205,
        filter: "lowpass",
        freq: 3600.0,
        filter_q: 1.0,
        filter_sweep: None,
        attack: 0.002,
        decay: 0.13,
        sustain: 0.12,
        release: 0.18,
        dur_mul: 0.62,
        spread_mul: 0.58,
        shimmer: false,
        max_live_dur: 0.7,
        layers: &GENERATED_CHORD_SALOON_PIANO_LAYERS,
    }
}

fn generated_native_chord_harp() -> NativeChordConfig {
    NativeChordConfig {
        root_wave: "triangle",
        wave: "sine",
        peak: 0.18,
        filter: "lowpass",
        freq: 4600.0,
        filter_q: 1.4,
        filter_sweep: None,
        attack: 0.002,
        decay: 0.1,
        sustain: 0.03,
        release: 0.36,
        dur_mul: 0.5,
        spread_mul: 1.45,
        shimmer: true,
        max_live_dur: 0.58,
        layers: &GENERATED_CHORD_HARP_LAYERS,
    }
}

fn generated_native_chord_warm_pad() -> NativeChordConfig {
    NativeChordConfig {
        root_wave: "sine",
        wave: "triangle",
        peak: 0.14,
        filter: "lowpass",
        freq: 1200.0,
        filter_q: 0.65,
        filter_sweep: Some(1700.0),
        attack: 0.11,
        decay: 0.24,
        sustain: 0.82,
        release: 0.62,
        dur_mul: 1.35,
        spread_mul: 0.25,
        shimmer: false,
        max_live_dur: 1.65,
        layers: &GENERATED_CHORD_WARM_PAD_LAYERS,
    }
}

fn generated_native_chord_glass() -> NativeChordConfig {
    NativeChordConfig {
        root_wave: "sine",
        wave: "sine",
        peak: 0.16,
        filter: "bandpass",
        freq: 1500.0,
        filter_q: 1.15,
        filter_sweep: None,
        attack: 0.004,
        decay: 0.2,
        sustain: 0.1,
        release: 0.44,
        dur_mul: 0.9,
        spread_mul: 0.85,
        shimmer: true,
        max_live_dur: 0.82,
        layers: &GENERATED_CHORD_GLASS_LAYERS,
    }
}

fn generated_native_chord_dusty_rhodes() -> NativeChordConfig {
    NativeChordConfig {
        root_wave: "triangle",
        wave: "triangle",
        peak: 0.155,
        filter: "lowpass",
        freq: 1550.0,
        filter_q: 0.72,
        filter_sweep: None,
        attack: 0.012,
        decay: 0.18,
        sustain: 0.44,
        release: 0.34,
        dur_mul: 0.96,
        spread_mul: 0.38,
        shimmer: false,
        max_live_dur: 1.05,
        layers: &GENERATED_CHORD_DUSTY_RHODES_LAYERS,
    }
}

fn generated_native_chord_felt_piano() -> NativeChordConfig {
    NativeChordConfig {
        root_wave: "triangle",
        wave: "triangle",
        peak: 0.145,
        filter: "lowpass",
        freq: 1900.0,
        filter_q: 0.82,
        filter_sweep: None,
        attack: 0.006,
        decay: 0.24,
        sustain: 0.22,
        release: 0.42,
        dur_mul: 0.82,
        spread_mul: 0.34,
        shimmer: false,
        max_live_dur: 0.96,
        layers: &GENERATED_CHORD_FELT_PIANO_LAYERS,
    }
}

fn generated_native_chord_cassette_keys() -> NativeChordConfig {
    NativeChordConfig {
        root_wave: "triangle",
        wave: "triangle",
        peak: 0.135,
        filter: "lowpass",
        freq: 1320.0,
        filter_q: 0.7,
        filter_sweep: None,
        attack: 0.018,
        decay: 0.18,
        sustain: 0.54,
        release: 0.44,
        dur_mul: 1.04,
        spread_mul: 0.45,
        shimmer: false,
        max_live_dur: 1.22,
        layers: &GENERATED_CHORD_CASSETTE_KEYS_LAYERS,
    }
}

fn generated_native_chord_muted_jazz_guitar() -> NativeChordConfig {
    NativeChordConfig {
        root_wave: "triangle",
        wave: "triangle",
        peak: 0.132,
        filter: "bandpass",
        freq: 1180.0,
        filter_q: 0.95,
        filter_sweep: None,
        attack: 0.004,
        decay: 0.09,
        sustain: 0.08,
        release: 0.16,
        dur_mul: 0.5,
        spread_mul: 0.72,
        shimmer: false,
        max_live_dur: 0.42,
        layers: &GENERATED_CHORD_MUTED_JAZZ_GUITAR_LAYERS,
    }
}

fn generated_native_chord_lofi_warm_pad() -> NativeChordConfig {
    NativeChordConfig {
        root_wave: "sine",
        wave: "triangle",
        peak: 0.115,
        filter: "lowpass",
        freq: 930.0,
        filter_q: 0.58,
        filter_sweep: Some(1180.0),
        attack: 0.18,
        decay: 0.3,
        sustain: 0.86,
        release: 0.72,
        dur_mul: 1.48,
        spread_mul: 0.22,
        shimmer: false,
        max_live_dur: 1.85,
        layers: &GENERATED_CHORD_LOFI_WARM_PAD_LAYERS,
    }
}

fn generated_native_lead_config(instrument: Option<&str>) -> NativeLeadConfig {
    match instrument.unwrap_or("pulse") {
        "soft" => generated_native_lead_soft(),
        "synth" => generated_native_lead_synth(),
        "bell" => generated_native_lead_bell(),
        "lead_guitar" => generated_native_lead_lead_guitar(),
        "distorted_lead_guitar" => generated_native_lead_distorted_lead_guitar(),
        "banjo" => generated_native_lead_banjo(),
        "harmonica" => generated_native_lead_harmonica(),
        "cowboy_whistle" => generated_native_lead_cowboy_whistle(),
        "trumpet" => generated_native_lead_trumpet(),
        "saxophone" => generated_native_lead_saxophone(),
        "mellow_vibes" => generated_native_lead_mellow_vibes(),
        "soft_pluck" => generated_native_lead_soft_pluck(),
        "mellow_sax" => generated_native_lead_mellow_sax(),
        "muted_trumpet" => generated_native_lead_muted_trumpet(),
        "tape_bell" => generated_native_lead_tape_bell(),
        _ => generated_native_lead_pulse(),
    }
}

const GENERATED_LEAD_PULSE_EXTRAS: [NativeLeadExtraConfig; 0] = [];

const GENERATED_LEAD_SOFT_EXTRAS: [NativeLeadExtraConfig; 0] = [];

const GENERATED_LEAD_SYNTH_EXTRAS: [NativeLeadExtraConfig; 0] = [];

const GENERATED_LEAD_BELL_EXTRAS: [NativeLeadExtraConfig; 1] = [
    NativeLeadExtraConfig {
        freq_mul: 2.0,
        midi_offset: 0.0,
        wave: "sine",
        peak: 0.022,
        filter: "lowpass",
        freq: 3200.0,
        offset: 0.012,
        dur_mul: 0.42,
        max_dur: None,
    }
];

const GENERATED_LEAD_LEAD_GUITAR_EXTRAS: [NativeLeadExtraConfig; 1] = [
    NativeLeadExtraConfig {
        freq_mul: 1.006,
        midi_offset: 0.0,
        wave: "square",
        peak: 0.035,
        filter: "lowpass",
        freq: 2600.0,
        offset: 0.006,
        dur_mul: 0.72,
        max_dur: None,
    }
];

const GENERATED_LEAD_DISTORTED_LEAD_GUITAR_EXTRAS: [NativeLeadExtraConfig; 1] = [
    NativeLeadExtraConfig {
        freq_mul: 0.996,
        midi_offset: 0.0,
        wave: "square",
        peak: 0.05,
        filter: "bandpass",
        freq: 2100.0,
        offset: 0.004,
        dur_mul: 0.68,
        max_dur: None,
    }
];

const GENERATED_LEAD_BANJO_EXTRAS: [NativeLeadExtraConfig; 2] = [
    NativeLeadExtraConfig {
        freq_mul: 2.01,
        midi_offset: 0.0,
        wave: "triangle",
        peak: 0.028,
        filter: "highpass",
        freq: 1500.0,
        offset: 0.004,
        dur_mul: 0.38,
        max_dur: Some(0.09),
    },
    NativeLeadExtraConfig {
        freq_mul: 0.997,
        midi_offset: 0.0,
        wave: "square",
        peak: 0.018,
        filter: "bandpass",
        freq: 2600.0,
        offset: 0.012,
        dur_mul: 0.48,
        max_dur: Some(0.13),
    }
];

const GENERATED_LEAD_HARMONICA_EXTRAS: [NativeLeadExtraConfig; 2] = [
    NativeLeadExtraConfig {
        freq_mul: 1.004,
        midi_offset: 0.0,
        wave: "triangle",
        peak: 0.035,
        filter: "bandpass",
        freq: 860.0,
        offset: 0.006,
        dur_mul: 0.92,
        max_dur: None,
    },
    NativeLeadExtraConfig {
        freq_mul: 2.0,
        midi_offset: 0.0,
        wave: "square",
        peak: 0.012,
        filter: "bandpass",
        freq: 2100.0,
        offset: 0.014,
        dur_mul: 0.42,
        max_dur: None,
    }
];

const GENERATED_LEAD_COWBOY_WHISTLE_EXTRAS: [NativeLeadExtraConfig; 1] = [
    NativeLeadExtraConfig {
        freq_mul: 2.0,
        midi_offset: 0.0,
        wave: "sine",
        peak: 0.014,
        filter: "lowpass",
        freq: 3600.0,
        offset: 0.01,
        dur_mul: 0.65,
        max_dur: None,
    }
];

const GENERATED_LEAD_TRUMPET_EXTRAS: [NativeLeadExtraConfig; 1] = [
    NativeLeadExtraConfig {
        freq_mul: 1.0,
        midi_offset: 12.0,
        wave: "sawtooth",
        peak: 0.018,
        filter: "bandpass",
        freq: 2400.0,
        offset: 0.008,
        dur_mul: 0.35,
        max_dur: None,
    }
];

const GENERATED_LEAD_SAXOPHONE_EXTRAS: [NativeLeadExtraConfig; 1] = [
    NativeLeadExtraConfig {
        freq_mul: 1.0,
        midi_offset: -12.0,
        wave: "sine",
        peak: 0.03,
        filter: "lowpass",
        freq: 760.0,
        offset: 0.004,
        dur_mul: 0.42,
        max_dur: None,
    }
];

const GENERATED_LEAD_MELLOW_VIBES_EXTRAS: [NativeLeadExtraConfig; 1] = [
    NativeLeadExtraConfig {
        freq_mul: 1.0,
        midi_offset: 12.0,
        wave: "sine",
        peak: 0.018,
        filter: "lowpass",
        freq: 2400.0,
        offset: 0.01,
        dur_mul: 0.48,
        max_dur: Some(0.18),
    }
];

const GENERATED_LEAD_SOFT_PLUCK_EXTRAS: [NativeLeadExtraConfig; 1] = [
    NativeLeadExtraConfig {
        freq_mul: 2.0,
        midi_offset: 0.0,
        wave: "sine",
        peak: 0.014,
        filter: "lowpass",
        freq: 2200.0,
        offset: 0.004,
        dur_mul: 0.45,
        max_dur: Some(0.12),
    }
];

const GENERATED_LEAD_MELLOW_SAX_EXTRAS: [NativeLeadExtraConfig; 1] = [
    NativeLeadExtraConfig {
        freq_mul: 1.0,
        midi_offset: -12.0,
        wave: "sine",
        peak: 0.018,
        filter: "lowpass",
        freq: 640.0,
        offset: 0.004,
        dur_mul: 0.46,
        max_dur: None,
    }
];

const GENERATED_LEAD_MUTED_TRUMPET_EXTRAS: [NativeLeadExtraConfig; 1] = [
    NativeLeadExtraConfig {
        freq_mul: 1.0,
        midi_offset: 12.0,
        wave: "triangle",
        peak: 0.012,
        filter: "bandpass",
        freq: 1700.0,
        offset: 0.006,
        dur_mul: 0.28,
        max_dur: None,
    }
];

const GENERATED_LEAD_TAPE_BELL_EXTRAS: [NativeLeadExtraConfig; 1] = [
    NativeLeadExtraConfig {
        freq_mul: 0.997,
        midi_offset: 12.0,
        wave: "sine",
        peak: 0.014,
        filter: "lowpass",
        freq: 2100.0,
        offset: 0.016,
        dur_mul: 0.38,
        max_dur: None,
    }
];

fn generated_native_lead_pulse() -> NativeLeadConfig {
    NativeLeadConfig {
        wave: "square",
        peak: 0.2,
        filter: "lowpass",
        freq: 2300.0,
        dur_mul: 1.0,
        extras: &GENERATED_LEAD_PULSE_EXTRAS,
    }
}

fn generated_native_lead_soft() -> NativeLeadConfig {
    NativeLeadConfig {
        wave: "triangle",
        peak: 0.16,
        filter: "lowpass",
        freq: 1700.0,
        dur_mul: 1.0,
        extras: &GENERATED_LEAD_SOFT_EXTRAS,
    }
}

fn generated_native_lead_synth() -> NativeLeadConfig {
    NativeLeadConfig {
        wave: "sawtooth",
        peak: 0.18,
        filter: "lowpass",
        freq: 1500.0,
        dur_mul: 0.95,
        extras: &GENERATED_LEAD_SYNTH_EXTRAS,
    }
}

fn generated_native_lead_bell() -> NativeLeadConfig {
    NativeLeadConfig {
        wave: "sine",
        peak: 0.105,
        filter: "lowpass",
        freq: 2600.0,
        dur_mul: 1.05,
        extras: &GENERATED_LEAD_BELL_EXTRAS,
    }
}

fn generated_native_lead_lead_guitar() -> NativeLeadConfig {
    NativeLeadConfig {
        wave: "sawtooth",
        peak: 0.16,
        filter: "bandpass",
        freq: 1800.0,
        dur_mul: 0.92,
        extras: &GENERATED_LEAD_LEAD_GUITAR_EXTRAS,
    }
}

fn generated_native_lead_distorted_lead_guitar() -> NativeLeadConfig {
    NativeLeadConfig {
        wave: "sawtooth",
        peak: 0.13,
        filter: "lowpass",
        freq: 2400.0,
        dur_mul: 0.86,
        extras: &GENERATED_LEAD_DISTORTED_LEAD_GUITAR_EXTRAS,
    }
}

fn generated_native_lead_banjo() -> NativeLeadConfig {
    NativeLeadConfig {
        wave: "triangle",
        peak: 0.13,
        filter: "bandpass",
        freq: 2100.0,
        dur_mul: 0.48,
        extras: &GENERATED_LEAD_BANJO_EXTRAS,
    }
}

fn generated_native_lead_harmonica() -> NativeLeadConfig {
    NativeLeadConfig {
        wave: "square",
        peak: 0.115,
        filter: "bandpass",
        freq: 1250.0,
        dur_mul: 1.18,
        extras: &GENERATED_LEAD_HARMONICA_EXTRAS,
    }
}

fn generated_native_lead_cowboy_whistle() -> NativeLeadConfig {
    NativeLeadConfig {
        wave: "sine",
        peak: 0.1,
        filter: "lowpass",
        freq: 3200.0,
        dur_mul: 1.12,
        extras: &GENERATED_LEAD_COWBOY_WHISTLE_EXTRAS,
    }
}

fn generated_native_lead_trumpet() -> NativeLeadConfig {
    NativeLeadConfig {
        wave: "square",
        peak: 0.14,
        filter: "bandpass",
        freq: 1650.0,
        dur_mul: 1.05,
        extras: &GENERATED_LEAD_TRUMPET_EXTRAS,
    }
}

fn generated_native_lead_saxophone() -> NativeLeadConfig {
    NativeLeadConfig {
        wave: "triangle",
        peak: 0.17,
        filter: "bandpass",
        freq: 940.0,
        dur_mul: 1.12,
        extras: &GENERATED_LEAD_SAXOPHONE_EXTRAS,
    }
}

fn generated_native_lead_mellow_vibes() -> NativeLeadConfig {
    NativeLeadConfig {
        wave: "sine",
        peak: 0.105,
        filter: "lowpass",
        freq: 2100.0,
        dur_mul: 1.15,
        extras: &GENERATED_LEAD_MELLOW_VIBES_EXTRAS,
    }
}

fn generated_native_lead_soft_pluck() -> NativeLeadConfig {
    NativeLeadConfig {
        wave: "triangle",
        peak: 0.112,
        filter: "lowpass",
        freq: 1650.0,
        dur_mul: 0.62,
        extras: &GENERATED_LEAD_SOFT_PLUCK_EXTRAS,
    }
}

fn generated_native_lead_mellow_sax() -> NativeLeadConfig {
    NativeLeadConfig {
        wave: "triangle",
        peak: 0.118,
        filter: "bandpass",
        freq: 820.0,
        dur_mul: 1.18,
        extras: &GENERATED_LEAD_MELLOW_SAX_EXTRAS,
    }
}

fn generated_native_lead_muted_trumpet() -> NativeLeadConfig {
    NativeLeadConfig {
        wave: "square",
        peak: 0.095,
        filter: "bandpass",
        freq: 1180.0,
        dur_mul: 0.98,
        extras: &GENERATED_LEAD_MUTED_TRUMPET_EXTRAS,
    }
}

fn generated_native_lead_tape_bell() -> NativeLeadConfig {
    NativeLeadConfig {
        wave: "sine",
        peak: 0.088,
        filter: "lowpass",
        freq: 1900.0,
        dur_mul: 1.04,
        extras: &GENERATED_LEAD_TAPE_BELL_EXTRAS,
    }
}

fn generated_guitar_tone_config(tone: Option<&str>) -> NativeGuitarToneConfig {
    match tone.unwrap_or("high_gain") {
        "clean" => generated_guitar_tone_clean(),
        "crunch" => generated_guitar_tone_crunch(),
        "metal" => generated_guitar_tone_metal(),
        "western_twang" => generated_guitar_tone_western_twang(),
        _ => generated_guitar_tone_high_gain(),
    }
}

fn generated_guitar_tone_clean() -> NativeGuitarToneConfig {
    NativeGuitarToneConfig {
        drive: 0.65,
        input: 0.62,
        peak: 0.086,
        lowpass: 4300.0,
        highpass: 90.0,
        body: 1.4,
        mid: 1.0,
        spread: 0.016,
        sustain: 1.08,
        mute: 0.085,
        scratch: 0.04,
    }
}

fn generated_guitar_tone_crunch() -> NativeGuitarToneConfig {
    NativeGuitarToneConfig {
        drive: 2.4,
        input: 0.8,
        peak: 0.092,
        lowpass: 3600.0,
        highpass: 100.0,
        body: 2.8,
        mid: 2.0,
        spread: 0.013,
        sustain: 0.98,
        mute: 0.074,
        scratch: 0.044,
    }
}

fn generated_guitar_tone_high_gain() -> NativeGuitarToneConfig {
    NativeGuitarToneConfig {
        drive: 4.2,
        input: 0.88,
        peak: 0.09,
        lowpass: 3250.0,
        highpass: 108.0,
        body: 3.7,
        mid: 2.6,
        spread: 0.01,
        sustain: 0.91,
        mute: 0.066,
        scratch: 0.042,
    }
}

fn generated_guitar_tone_metal() -> NativeGuitarToneConfig {
    NativeGuitarToneConfig {
        drive: 6.2,
        input: 0.92,
        peak: 0.088,
        lowpass: 3050.0,
        highpass: 115.0,
        body: 4.5,
        mid: 3.0,
        spread: 0.009,
        sustain: 0.86,
        mute: 0.06,
        scratch: 0.04,
    }
}

fn generated_guitar_tone_western_twang() -> NativeGuitarToneConfig {
    NativeGuitarToneConfig {
        drive: 1.25,
        input: 0.68,
        peak: 0.082,
        lowpass: 4700.0,
        highpass: 125.0,
        body: 1.1,
        mid: 2.4,
        spread: 0.02,
        sustain: 0.72,
        mute: 0.07,
        scratch: 0.034,
    }
}
